import { AIChatBox, Message } from "@/components/AIChatBox";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, BookOpen, CheckCircle2, FileText, History, Image as ImageIcon, LockKeyhole, Plus, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

export default function Ask() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [subjectId, setSubjectId] = useState("all");
  const [sources, setSources] = useState<Array<{ title: string; pageRef: string; visualUrl: string | null; visualIsImage: boolean; visualCaption: string | null }>>([]);
  const [conversationId, setConversationId] = useState<number | null>(null);
  const subjects = trpc.subjects.list.useQuery();
  const history = trpc.ai.history.useQuery();
  const conversation = trpc.ai.conversation.useQuery({ conversationId: conversationId || 0 }, { enabled: Boolean(conversationId) });
  const ask = trpc.ai.ask.useMutation({ onSuccess: response => { setConversationId(response.conversationId); setMessages(current => [...current, { role: "assistant", content: response.answer }]); setSources(response.sources); history.refetch(); }, onError: error => { toast.error(error.message); setMessages(current => current.slice(0, -1)); } });
  const selectedLabel = useMemo(() => subjectId === "all" ? "All authorized notes" : subjects.data?.find(item => String(item.id) === subjectId)?.name || "Selected subject", [subjectId, subjects.data]);
  useEffect(() => { if (!conversationId || !conversation.data) return; setMessages(conversation.data.flatMap(item => [{ role: "user" as const, content: item.question }, { role: "assistant" as const, content: item.answer }])); setSources([]); }, [conversationId, conversation.data]);
  const send = (content: string) => { setMessages(current => [...current, { role: "user", content }]); ask.mutate({ question: content, subjectId: subjectId === "all" ? undefined : Number(subjectId), conversationId: conversationId || undefined }); };

  return (
    <div className="mx-auto max-w-[1320px] space-y-7">
      <section className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.15em] text-coral-dark"><Sparkles className="size-4" /> Grounded study assistant</div><h1 className="font-display text-3xl font-black tracking-tight sm:text-5xl">Ask your notes</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Ask a specific question and StudyNow will retrieve only your private notes and permitted saved class material.</p></div><div className="flex items-center gap-2 rounded-2xl border border-teal/15 bg-teal/5 px-4 py-3 text-xs font-bold text-teal-dark"><LockKeyhole className="size-4" /> Authorized sources only</div></section>
      <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
        <div className="space-y-4"><Card className="border-border/70 bg-card shadow-soft"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">Search scope</p><p className="mt-1 text-sm font-bold">{selectedLabel}</p></div><Select value={subjectId} onValueChange={setSubjectId}><SelectTrigger className="w-full rounded-xl bg-white sm:w-64"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All authorized notes</SelectItem>{subjects.data?.map(subject => <SelectItem key={subject.id} value={String(subject.id)}>{subject.name}</SelectItem>)}</SelectContent></Select></CardContent></Card><AIChatBox messages={messages} onSendMessage={send} isLoading={ask.isPending} height="560px" placeholder="Ask about a definition, process, formula, or diagram…" emptyStateMessage="Your evidence-backed study session starts here" suggestedPrompts={["Summarize the key ideas in this subject", "What should I compare before the exam?", "Explain the most recent concept step by step"]} /></div>
        <aside className="space-y-4"><Card className="border-border/70 bg-white/70 shadow-soft"><CardHeader><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><History className="size-5" /></div><div><CardTitle className="font-display text-lg font-extrabold">Study sessions</CardTitle><p className="mt-1 text-xs text-muted-foreground">Pick up where you left off</p></div></div><Button variant="ghost" size="sm" className="rounded-lg px-2" onClick={() => { setConversationId(null); setMessages([]); setSources([]); }}><Plus className="mr-1 size-3.5" />New</Button></div></CardHeader><CardContent>{history.isLoading ? <p className="text-xs text-muted-foreground">Loading sessions…</p> : history.data?.length ? <div className="space-y-2">{history.data.slice(0, 5).map(item => <Button key={item.id} variant={conversationId === item.id ? "secondary" : "ghost"} className="h-auto w-full justify-start rounded-xl px-3 py-2 text-left" onClick={() => { setConversationId(item.id); setMessages([]); }}><span className="line-clamp-2 text-xs font-bold">{item.title || "Untitled study session"}</span></Button>)}</div> : <p className="text-xs leading-5 text-muted-foreground">Your next question will create a saved session.</p>}</CardContent></Card><Card className="border-border/70 bg-white/70 shadow-soft"><CardHeader><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-coral/10 text-coral-dark"><CheckCircle2 className="size-5" /></div><div><CardTitle className="font-display text-lg font-extrabold">Evidence first</CardTitle><p className="mt-1 text-xs text-muted-foreground">How answers stay useful</p></div></div></CardHeader><CardContent className="space-y-4 text-sm leading-6 text-muted-foreground"><p><strong className="text-foreground">1. Retrieve.</strong> Relevant chunks are selected from your authorized notes.</p><p><strong className="text-foreground">2. Explain.</strong> The model answers from those chunks, not from open web search.</p><p><strong className="text-foreground">3. Cite.</strong> Each answer keeps note and section references beside the response.</p><div className="rounded-xl bg-muted/70 p-3 text-xs leading-5">If the material is not in your stored notes, the assistant will say so rather than inventing a citation.</div></CardContent></Card><Card className="border-border/70 bg-primary text-primary-foreground shadow-soft"><CardContent className="p-5"><BookOpen className="size-5" /><p className="mt-5 font-display text-lg font-extrabold">Better prompts, better recall</p><p className="mt-2 text-sm leading-6 text-primary-foreground/75">Ask for a comparison, a step-by-step explanation, or the page where a concept appears.</p></CardContent></Card></aside>
      </section>
      {sources.length > 0 && <section className="space-y-4"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Retrieved evidence</p><h2 className="mt-1 font-display text-2xl font-extrabold">Sources behind the answer</h2></div><Badge variant="outline" className="rounded-full">{sources.length} cited</Badge></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sources.map((source, index) => <Card key={`${source.title}-${index}`} className="overflow-hidden border-border/70 bg-card shadow-soft"><CardContent className="p-0">{source.visualUrl && source.visualIsImage ? <img src={source.visualUrl} alt={source.visualCaption || `Visual from ${source.title}`} className="h-36 w-full object-cover" /> : <div className="grid h-24 place-items-center bg-muted/60">{source.visualUrl ? <a href={source.visualUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-border bg-white px-3 py-2 text-xs font-bold text-primary hover:bg-muted"><ImageIcon className="size-4" />Open visual source</a> : <ImageIcon className="size-6 text-muted-foreground/60" />}</div>}<div className="p-4"><div className="flex items-start justify-between gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary"><FileText className="size-4" /></div><span className="text-[11px] font-bold uppercase tracking-[0.12em] text-muted-foreground">Source {index + 1}</span></div><p className="mt-4 line-clamp-2 font-bold">{source.title}</p><p className="mt-1 text-xs font-semibold text-primary">{source.pageRef}</p>{source.visualCaption && <p className="mt-2 text-xs leading-5 text-muted-foreground">{source.visualCaption}</p>}<Button variant="ghost" size="sm" className="mt-3 -ml-2 rounded-lg px-2">View source <ArrowUpRight className="ml-1 size-3.5" /></Button></div></CardContent></Card>)}</div></section>}
    </div>
  );
}
