import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, BookOpen, FileText, Library, Plus, Search, ShieldCheck, Sparkles, UploadCloud } from "lucide-react";
import { Link } from "wouter";

const roleLabel = (role?: string | null) => role === "admin" ? "Administrator" : role === "teacher" ? "Teacher" : "Student";
const shortDate = (value?: Date | string | null) => value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "—";

export default function Dashboard() {
  const { user } = useAuth();
  const { data, isLoading } = trpc.dashboard.summary.useQuery();
  const isTeacher = data?.role === "teacher";
  const isAdmin = data?.role === "admin";
  const notes = data?.notes || [];
  const resources = data?.resources || [];
  const subjects = data?.subjects || [];

  return (
    <div className="mx-auto max-w-[1320px] space-y-8">
      <section className="relative overflow-hidden rounded-[28px] border border-border/70 bg-card p-6 shadow-card sm:p-8 lg:p-10">
        <div className="absolute -right-12 -top-20 size-64 rounded-full bg-teal/10 blur-3xl" /><div className="absolute bottom-0 right-24 size-36 rounded-full bg-coral/10 blur-3xl" />
        <div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-primary/15 bg-primary/5 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.12em] text-primary"><span className="size-1.5 rounded-full bg-primary" /> {roleLabel(user?.role)} workspace</div><h1 className="font-display text-3xl font-black tracking-tight sm:text-5xl">Good to see you, {user?.name?.split(" ")[0] || "there"}.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground sm:text-base">Your study material has a place to land. Pick a subject, open a note, or ask a question when you are ready.</p></div><div className="flex flex-wrap gap-3"><Link href={isTeacher ? "/teacher" : isAdmin ? "/admin" : "/notes"}><Button className="rounded-xl shadow-lift">{isTeacher ? "Open teacher portal" : isAdmin ? "Open admin workspace" : "Open my notes"}<ArrowUpRight className="ml-2 size-4" /></Button></Link>{!isTeacher && !isAdmin && <Link href="/ask"><Button variant="outline" className="rounded-xl bg-white/70"><Sparkles className="mr-2 size-4 text-coral" /> Ask your notes</Button></Link>}</div></div>
      </section>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {[{ label: isTeacher ? "Managed subjects" : "Your subjects", value: subjects.length, icon: BookOpen, tone: "text-primary bg-primary/10" }, { label: isTeacher ? "Resources" : "Private notes", value: isTeacher ? resources.length : notes.length, icon: FileText, tone: "text-teal-dark bg-teal/10" }, { label: isTeacher ? "Assigned classes" : "Saved resources", value: isTeacher ? (data?.classes?.length || 0) : resources.length, icon: Library, tone: "text-coral-dark bg-coral/10" }, { label: "Access status", value: "Clear", icon: ShieldCheck, tone: "text-emerald-700 bg-emerald-100" }].map(({ label, value, icon: Icon, tone }) => <Card key={label} className="border-border/70 shadow-soft"><CardContent className="flex items-center justify-between p-5"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">{label}</p><div className="mt-2 font-display text-3xl font-black tracking-tight">{isLoading ? <Skeleton className="h-9 w-16" /> : value}</div></div><div className={`grid size-11 place-items-center rounded-2xl ${tone}`}><Icon className="size-5" /></div></CardContent></Card>)}
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
        <Card className="border-border/70 shadow-soft"><CardHeader className="flex flex-row items-center justify-between space-y-0"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">{isTeacher ? "Your publishing desk" : "Your subjects"}</p><CardTitle className="mt-1 font-display text-xl font-extrabold">{isTeacher ? "Keep each class in motion" : "Start from the structure"}</CardTitle></div>{!isTeacher && !isAdmin && <Link href="/notes"><Button variant="outline" size="sm" className="rounded-lg bg-white/60"><Plus className="mr-1 size-4" /> Add note</Button></Link>}</CardHeader><CardContent>{isLoading ? <div className="space-y-3"><Skeleton className="h-16 w-full" /><Skeleton className="h-16 w-full" /><Skeleton className="h-16 w-full" /></div> : subjects.length ? <div className="grid gap-3 sm:grid-cols-2">{subjects.slice(0, 6).map(subject => <Link key={subject.id} href={`/notes?subject=${subject.id}`}><div className="group rounded-2xl border border-border/70 bg-white/60 p-4 transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-soft"><div className="flex items-start justify-between gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><BookOpen className="size-4" /></div><ArrowUpRight className="size-4 text-muted-foreground transition group-hover:text-primary" /></div><p className="mt-4 font-bold">{subject.name}</p><p className="mt-1 text-xs text-muted-foreground">{subject.code || "Personal subject"}{subject.term ? ` · ${subject.term}` : ""}</p></div></Link>)}</div> : <div className="rounded-2xl border border-dashed border-border p-8 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><BookOpen className="size-5" /></div><p className="mt-4 font-bold">No subjects yet</p><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-muted-foreground">Create your first subject to give your notes a reliable home and make future retrieval more precise.</p>{!isAdmin && <Link href="/notes"><Button className="mt-5 rounded-xl">Create a subject</Button></Link>}</div>}</CardContent></Card>

        <Card className="border-border/70 shadow-soft"><CardHeader><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">{isTeacher ? "Publication queue" : "Recent notes"}</p><CardTitle className="mt-1 font-display text-xl font-extrabold">A quick return point</CardTitle></CardHeader><CardContent>{isLoading ? <div className="space-y-3"><Skeleton className="h-14 w-full" /><Skeleton className="h-14 w-full" /><Skeleton className="h-14 w-full" /></div> : (isTeacher ? resources : notes).length ? <div className="space-y-2">{(isTeacher ? resources : notes).slice(0, 5).map((item: any) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-border/60 p-3"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-muted"><FileText className="size-4 text-muted-foreground" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{item.title}</p><p className="mt-0.5 text-xs text-muted-foreground">{isTeacher ? item.status : item.source || "Private note"} · {shortDate(item.updatedAt || item.createdAt)}</p></div><Badge variant="outline" className="hidden capitalize sm:inline-flex">{isTeacher ? item.status : "stored"}</Badge></div>)}</div> : <div className="rounded-2xl bg-muted/60 p-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-card text-primary"><UploadCloud className="size-4" /></div><div><p className="text-sm font-bold">Nothing here yet</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Your next upload will appear in this return point.</p></div></div></div>}</CardContent></Card>
      </section>

      <section className="grid gap-4 md:grid-cols-3"><Link href="/notes"><Card className="group border-border/70 bg-primary text-primary-foreground shadow-soft transition hover:-translate-y-1 hover:shadow-lift"><CardContent className="p-6"><FileText className="size-5" /><h3 className="mt-8 font-display text-lg font-extrabold">Build your library</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/75">Store rich text and source files by subject, with clear processing states.</p><span className="mt-5 inline-flex items-center text-xs font-bold uppercase tracking-[0.12em]">Open notes <ArrowUpRight className="ml-2 size-3" /></span></CardContent></Card></Link><Link href="/resources"><Card className="group border-border/70 bg-teal text-white shadow-soft transition hover:-translate-y-1 hover:shadow-lift"><CardContent className="p-6"><Library className="size-5" /><h3 className="mt-8 font-display text-lg font-extrabold">Browse class material</h3><p className="mt-2 text-sm leading-6 text-white/75">See resources published to classes you are allowed to access.</p><span className="mt-5 inline-flex items-center text-xs font-bold uppercase tracking-[0.12em]">Open library <ArrowUpRight className="ml-2 size-3" /></span></CardContent></Card></Link><Link href="/ask"><Card className="group border-border/70 bg-coral text-white shadow-soft transition hover:-translate-y-1 hover:shadow-lift"><CardContent className="p-6"><Sparkles className="size-5" /><h3 className="mt-8 font-display text-lg font-extrabold">Ask from evidence</h3><p className="mt-2 text-sm leading-6 text-white/75">Search permitted notes and see the source behind each answer.</p><span className="mt-5 inline-flex items-center text-xs font-bold uppercase tracking-[0.12em]">Ask a question <ArrowUpRight className="ml-2 size-3" /></span></CardContent></Card></Link></section>
    </div>
  );
}
