import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { BookOpen, Download, FileText, FolderHeart, Loader2, Search, Sparkles, Users, Bookmark } from "lucide-react";
import { useMemo, useState } from "react";

export default function Resources() {
  const [search, setSearch] = useState("");
  const [previewId, setPreviewId] = useState<number | null>(null);
  const [saveOpen, setSaveOpen] = useState(false);
  const [pendingSaveId, setPendingSaveId] = useState<number | null>(null);
  const [destinationSubjectId, setDestinationSubjectId] = useState("");
  const utils = trpc.useUtils();
  const subjects = trpc.subjects.list.useQuery();
  const publishedInput = useMemo(() => ({ search: search.trim() || undefined }), [search]);
  const resources = trpc.library.published.useQuery(publishedInput);
  const saved = trpc.library.saved.useQuery();
  const preview = trpc.library.get.useQuery({ resourceId: previewId || 0 }, { enabled: Boolean(previewId) });
  const save = trpc.library.save.useMutation({ onSuccess: () => { toast.success("Saved to your personal library"); setSaveOpen(false); setPendingSaveId(null); utils.library.saved.invalidate(); utils.dashboard.summary.invalidate(); }, onError: error => toast.error(error.message) });
  const requestSave = (resourceId: number) => { if (!subjects.data?.length) return toast.error("Create a personal subject before saving resources."); setPendingSaveId(resourceId); setDestinationSubjectId(String(subjects.data[0].id)); setSaveOpen(true); };

  return (
    <div className="mx-auto max-w-[1320px] space-y-7">
      <section className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.15em] text-teal-dark"><Users className="size-4" /> Shared with your classes</div><h1 className="font-display text-3xl font-black tracking-tight sm:text-5xl">Class library</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Browse class notes and syllabus resources your teachers have published to you. Save what you want to keep in your own study flow.</p></div><div className="flex items-center gap-2 rounded-2xl border border-border/70 bg-white/70 px-4 py-3 text-sm font-bold"><FolderHeart className="size-4 text-coral" /> {saved.data?.length || 0} saved</div></section>
      <div className="relative max-w-2xl"><Search className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search class resources…" className="h-12 rounded-xl border-border/70 bg-white/75 pl-11" /></div>
      {resources.isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Skeleton className="h-52 rounded-2xl" /><Skeleton className="h-52 rounded-2xl" /><Skeleton className="h-52 rounded-2xl" /></div> : resources.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{resources.data.map(resource => <Card key={resource.id} className="border-border/70 bg-card shadow-soft transition hover:-translate-y-1 hover:shadow-lift"><CardHeader><div className="flex items-start justify-between gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-teal/10 text-teal-dark"><FileText className="size-5" /></div><Badge className="rounded-full bg-teal/10 text-teal-dark hover:bg-teal/10">Published</Badge></div><CardTitle className="mt-4 font-display text-xl font-extrabold tracking-tight">{resource.title}</CardTitle></CardHeader><CardContent><p className="line-clamp-2 min-h-10 text-sm leading-6 text-muted-foreground">{resource.description || "A teacher-shared resource available to your assigned class."}</p><div className="mt-5 flex items-center justify-between border-t border-border/70 pt-4"><span className="text-xs font-semibold text-muted-foreground">Class material</span><div className="flex gap-1"><Button variant="ghost" size="sm" className="rounded-lg" onClick={() => setPreviewId(resource.id)}>Preview</Button><Button size="sm" className="rounded-lg" disabled={save.isPending} onClick={() => requestSave(resource.id)}><Bookmark className="mr-1 size-3.5" />Save</Button></div></div></CardContent></Card>)}</div> : <Card className="border-dashed border-border bg-white/50 shadow-none"><CardContent className="grid place-items-center px-6 py-16 text-center"><div className="grid size-14 place-items-center rounded-2xl bg-teal/10 text-teal-dark"><Users className="size-6" /></div><h2 className="mt-5 font-display text-xl font-extrabold">No shared resources yet</h2><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">When a teacher publishes to one of your assigned classes, the resource will appear here. You can then preview, download, or save it.</p></CardContent></Card>}

      <section className="grid gap-4 md:grid-cols-3"><Card className="border-border/70 bg-teal text-white shadow-soft"><CardContent className="p-5"><Sparkles className="size-5" /><p className="mt-5 font-display text-lg font-extrabold">A smaller search space</p><p className="mt-2 text-sm leading-6 text-white/75">Your AI workspace can use saved class resources as evidence alongside private notes.</p></CardContent></Card><Card className="border-border/70 bg-white/70 shadow-soft"><CardContent className="p-5"><Download className="size-5 text-primary" /><p className="mt-5 font-display text-lg font-extrabold">Keep the original</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Downloads always point back to the securely stored source file.</p></CardContent></Card><Card className="border-border/70 bg-coral text-white shadow-soft"><CardContent className="p-5"><BookOpen className="size-5" /><p className="mt-5 font-display text-lg font-extrabold">Study your way</p><p className="mt-2 text-sm leading-6 text-white/75">Save resources into your personal subject flow when they are relevant to your revision.</p></CardContent></Card></section>

      <Dialog open={Boolean(previewId)} onOpenChange={open => !open && setPreviewId(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{preview.data?.resource.title || "Resource preview"}</DialogTitle><DialogDescription>{preview.data?.resource.description || "Teacher-shared class material"}</DialogDescription></DialogHeader>{preview.isLoading ? <div className="space-y-3"><Skeleton className="h-24 w-full" /><Skeleton className="h-12 w-full" /></div> : preview.data ? <div className="space-y-4">{preview.data.note?.content && <div className="whitespace-pre-wrap rounded-2xl bg-muted/60 p-5 text-sm leading-7">{preview.data.note.content}</div>}{preview.data.files?.map(file => <div key={file.id} className="flex items-center gap-3 rounded-2xl border border-border/70 p-4"><FileText className="size-5 text-primary" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{file.originalName}</p><p className="mt-1 text-xs text-muted-foreground">{file.mimeType} · {(file.sizeBytes / 1024 / 1024).toFixed(2)} MB</p></div>{file.mimeType.startsWith("image/") ? <img src={file.storageUrl} alt={file.originalName} className="size-16 rounded-xl object-cover" /> : <a href={file.storageUrl} target="_blank" rel="noreferrer" className="inline-flex items-center rounded-lg border border-border px-3 py-2 text-sm font-bold hover:bg-muted"><Download className="mr-2 size-4" />Download</a>}</div>)}</div> : <p className="text-sm text-muted-foreground">This resource is no longer available or you do not have access.</p>}<DialogFooter><Button variant="outline" className="rounded-xl" onClick={() => setPreviewId(null)}>Close</Button>{preview.data && <Button className="rounded-xl" disabled={save.isPending} onClick={() => previewId && requestSave(previewId)}><Bookmark className="mr-2 size-4" />Save to my library</Button>}</DialogFooter></DialogContent></Dialog>
      <Dialog open={saveOpen} onOpenChange={setSaveOpen}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Save to a personal subject</DialogTitle><DialogDescription>Choose where this class resource should appear in your private study library.</DialogDescription></DialogHeader><div className="space-y-2 py-2"><Label>Destination subject</Label><Select value={destinationSubjectId} onValueChange={setDestinationSubjectId}><SelectTrigger><SelectValue placeholder="Choose a subject" /></SelectTrigger><SelectContent>{subjects.data?.map(subject => <SelectItem key={subject.id} value={String(subject.id)}>{subject.name}</SelectItem>)}</SelectContent></Select></div><DialogFooter><Button variant="outline" onClick={() => setSaveOpen(false)}>Cancel</Button><Button disabled={!pendingSaveId || !destinationSubjectId || save.isPending} onClick={() => pendingSaveId && save.mutate({ resourceId: pendingSaveId, personalSubjectId: Number(destinationSubjectId) })}>{save.isPending ? <Loader2 className="mr-2 size-4 animate-spin" /> : <Bookmark className="mr-2 size-4" />}Save resource</Button></DialogFooter></DialogContent></Dialog>
    </div>
  );
}
